---
eight_bit:
  Black:
    hl24: Black
    hl8: Black
  Blue:
    hl24: DarkBlue
    hl8: DarkBlue
  BrightBlack:
    hl24: Grey
    hl8: Grey
  BrightBlue:
    hl24: LightBlue
    hl8: LightBlue
  BrightCyan:
    hl24: LightCyan
    hl8: LightCyan
  BrightGreen:
    hl24: LightGreen
    hl8: LightGreen
  BrightMagenta:
    hl24: LightMagenta
    hl8: LightMagenta
  BrightRed:
    hl24: LightRed
    hl8: LightRed
  BrightWhite:
    hl24: White
    hl8: White
  BrightYellow:
    hl24: LightYellow
    hl8: LightYellow
  Cyan:
    hl24: DarkCyan
    hl8: DarkCyan
  Green:
    hl24: DarkGreen
    hl8: DarkGreen
  Magenta:
    hl24: DarkMagenta
    hl8: DarkMagenta
  Red:
    hl24: DarkRed
    hl8: DarkRed
  White:
    hl24: LightGray
    hl8: LightGray
  Yellow:
    hl24: DarkYellow
    hl8: DarkYellow
