---
ignore:
  name:
  - .DS_Store
  - .directory
  - thumbs.db
  - .git
  path: []
options:
  follow: true
  keymap:
    bigger:
    - +
    - '='
    change_dir:
    - b
    change_focus:
    - c
    change_focus_up:
    - C
    clear_filter:
    - F
    - E
    clear_selection:
    - S
    collapse:
    - <s-tab>
    - '`'
    copy:
    - p
    copy_name:
    - y
    cut:
    - x
    delete:
    - d
    filter:
    - f
    h_split:
    - W
    jump_to_current:
    - J
    new:
    - a
    open_sys:
    - o
    primary:
    - <enter>
    quit:
    - q
    refocus:
    - '~'
    refresh:
    - <c-r>
    rename:
    - r
    secondary:
    - <tab>
    - <2-leftmouse>
    select:
    - s
    smaller:
    - '-'
    - _
    stat:
    - K
    tertiary:
    - <m-enter>
    - <middlemouse>
    toggle_follow: []
    toggle_hidden:
    - .
    toggle_version_control: []
    trash:
    - t
    v_split:
    - w
  lang: null
  mimetypes:
    ignore_exts:
    - .ts
    warn:
    - audio
    - font
    - image
    - video
  open_left: true
  page_increment: 5
  polling_rate: 2.0
  session: true
  show_hidden: false
  sort_by:
  - is_folder
  - ext
  - fname
  use_icons: true
  version_control:
    enable: true
  width: 40
view:
  highlights:
    quickfix: Label
    version_control: Comment
  time_format: '%Y-%m-%d %H:%M'
  window_options:
    cursorline: true
    number: false
    relativenumber: false
    signcolumn: 'no'
    winfixwidth: true
    wrap: false
