---
ignore:
  name_exact:
    - .DS_Store
    - .directory
    - thumbs.db
    - .git
  name_glob: []
  path_glob: []
keymap:
  bigger:
    - +
    - "="
  change_dir:
    - b
  change_focus:
    - c
  change_focus_up:
    - C
  clear_filter:
    - F
  clear_selection:
    - S
  collapse:
    - <s-tab>
    - "`"
  copy:
    - p
  copy_name:
    - y
  cut:
    - x
  delete:
    - d
  filter:
    - f
  h_split:
    - W
  jump_to_current:
    - J
  new:
    - a
  open_sys:
    - o
  primary:
    - <enter>
  quit:
    - q
  refocus:
    - "~"
  refresh:
    - <c-r>
  rename:
    - r
  secondary:
    - <tab>
    - <2-leftmouse>
  select:
    - s
  smaller:
    - "-"
    - _
  stat:
    - K
  tertiary:
    - <m-enter>
    - <middlemouse>
  toggle_follow: []
  toggle_hidden:
    - .
  toggle_version_control: []
  trash:
    - t
  v_split:
    - w
options:
  follow: true
  lang: null
  mimetypes:
    allow_exts:
      - .ts
    warn:
      - audio
      - font
      - image
      - video
  page_increment: 5
  polling_rate: 2.0
  session: true
  show_hidden: false
  version_control:
    enable: true
theme:
  highlights:
    ignored: Comment
    quickfix: Label
    version_control: Comment
  icon_glyph_set: devicons
  icon_colour_set: github
  text_colour_set: env
  discrete_colour_map:
    Black: Black
    Red: Red
    Green: Green
    Yellow: Yellow
    Blue: Blue
    Magenta: Magenta
    Cyan: Cyan
    White: White

    BrightBlack: BrightBlack
    BrightRed: BrightRed
    BrightGreen: BrightGreen
    BrightYellow: BrightYellow
    BrightBlue: BrightBlue
    BrightMagenta: BrightMagenta
    BrightCyan: BrightCyan
    BrightWhite: BrightWhite
view:
  open_direction: left
  sort_by:
    - is_folder
    - ext
    - file_name
  time_format: "%Y-%m-%d %H:%M"
  width: 40
  window_options:
    cursorline: true
    number: false
    relativenumber: false
    signcolumn: "no"
    winfixwidth: true
    wrap: false
